version: '3'

services:
  game_server:
    build: ./srv
    container_name: game_server_arc
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      - /public:/public
  
  nginx:
    image: nginx:stable-alpine
    container_name: game_nginx_arc
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf 
    depends_on:
      - game_server